name: Publish Phantom NuGet Package

on:
  pull_request:
    branches: [main]

env:
  project: .\src\Phantom\Phantom.csproj

jobs:
  build:
    name: Build
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "name=version::${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"

      - name: Display version
        run: echo ${{ env.version }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: preview

      - name: Restore dependencies
        run: dotnet restore ${{ env.project }}

      - name: Build
        run: dotnet build ${{ env.project }} -c release --no-restore

      - name: Pack
        run: dotnet pack ${{ env.project }} -c release --no-build --no-restore --output .\artifacts -p:PackageVersion=${{ env.version }}

      - name: Display artifacts
        run: ls .\artifacts
